"e visual bell instead of beeping
set vb

" incremental search
set incsearch

" syntax highlighting
set bg=light
syntax on

" autoindent
autocmd FileType perl set autoindent|set smartindent
autocmd FileType python set autoindent|set smartindent
autocmd FileType php set autoindent|set smartindent

" 4 space tabs
autocmd FileType perl set tabstop=4|set shiftwidth=4|set expandtab|set softtabstop=4
autocmd FileType python set tabstop=4|set shiftwidth=4|set expandtab|set softtabstop=4
autocmd FileType php set tabstop=4|set shiftwidth=4|set expandtab|set softtabstop=4


" show matching brackets
autocmd FileType perl set showmatch
autocmd FileType python set showmatch
autocmd FileType php set showmatch

" show line numbers
autocmd FileType perl set number
autocmd FileType python set number
autocmd FileType php set number

" check perl code with :make
autocmd FileType perl set makeprg=perl\ -c\ %\ $*
autocmd FileType perl set errorformat=%f:%l:%m
autocmd FileType perl set autowrite
autocmd FileType python set makeprg=python\ -t\ %\ $*
autocmd FileType python set errorformat=%f:%l:%m
autocmd FileType python set autowrite

" dont use Q for Ex mode
map Q :q

" make tab in v mode ident code
vmap <tab> >gv
vmap <s-tab> <gv

" make tab in normal mode ident code
nmap <tab> I<tab><esc>
nmap <s-tab> ^i<bs><esc>

" paste mode - this will avoid unexpected effects when you
" cut or copy some text from one window and paste it in Vim.
set pastetoggle=<F11>

" comment/uncomment blocks of code (in vmode)
vmap _c :s/^/#/gi<Enter>
vmap _C :s/^#//gi<Enter>

" my perl includes pod
let perl_include_pod = 1

" syntax color complex things like @{${"foo"}}
let perl_extended_vars = 1

" vim-markdown plugin
let g:vim_markdown_folding_disabled=1 "new line at the end.
let g:vim_markdown_initial_foldlevel=1
let g:vim_markdown_frontmatter=1
let g:vim_markdown_math=1

"code sniffer/messdetector plugin
"let g:phpqa_codesniffer_args = '--standard=Zend'
"let g:phpqa_codesniffer_args = '--standard=/path/to/xml/file.xml --tab-width=4'
"let g:phpqa_codesniffer_cmd='/path/to/phpcs'
"let g:phpqa_codesniffer_autorun = 0
"let g:phpqa_messdetector_ruleset = '/path/to/phpmd.xml'
"let g:phpqa_messdetector_cmd='/path/to/phpmd'
"let g:phpqa_messdetector_autorun = 0

" Tidy selected lines (or entire file) with _t:
"http://perltidy.sourceforge.net/
nnoremap <silent> _t :%!perltidy -q<Enter>
vnoremap <silent> _t :!perltidy -q<Enter>


" Deparse obfuscated code - nada de ofuscar
"nnoremap <silent> _d :.!perl -MO=Deparse 2>/dev/null<cr>
"vnoremap <silent> _d :!perl -MO=Deparse 2>/dev/null<cr>

nnoremap ' :wa<CR>:!dcop konsole-`pidof konsole` session-1 sendSession r<CR><CR>

" TMUX
if &term == "screen"
        set t_kN=^[[6;*~
        set t_kP=^[[5;*~
endif

set encoding=utf-8
syntax enable


"Pathogen package manager for vim
execute pathogen#infect()
call pathogen#helptags()

"All plugins should be before pathogen#infect
"solarized
colorscheme solarized
set background=dark

"NERDtree
"autocmd vimenter * NERDTree    //abrir al iniciar VIM
map <C-t> :NERDTreeToggle<CR>

"supertab // instalado con pacman //pacman -Syu vim-supertab
"Pathogen package manager for vim
filetype plugin indent on

"laravel config // mode command
nmap <leader>lc :e composer.json<cr>
nmap <leader>lcd :e app/config/database.php<cr>
nmap <leader>lca :e app/config/app.php<cr>
nmap <leader>lr :e app/routes.php<cr>

"phpcomplete-extended-laravel depende de phpcomplete-extended y este depende
"de vimproc y tiene que ser compilado ojo.. y vim-unite
