library("arules")
library("arulesViz")
t = read.transactions("C:/somethingnull/rapidminer/transacciones.basket", sep=',', cols=c(1), format="basket")
image(tr)
summary(tr)
itemFrequencyPlot(tr, supp=0.1)
itemFrequencyPlot(tr, supp=0.05)
rules = apriori(tr, parameter= list(supp=0.1, conf=0.9))
inspect(rules)
par(cex=0.5)
plot(rules, method="graph", control=list(type="items"))
plot(rules, method="grouped")
saveAsGraph(rules, file="rulestransaction01.graphml")
rules = apriori(tr, parameter= list(supp=0.03, conf=0.9))
inspect(rules)
plot(rules, method="graph", control=list(type="items"))
plot(rules, method="grouped")


