#4.7 [Mathematical] For some distributions,
# the sample data can be summarized by a few sufficient statistics without loss of any information
# about the population parameters. However, this assumes that the data values are really generated 
#by the assumed population distribution, which is rarely exactly true when working with a real data set. 
#Hence, in practice, reducing the data to sufficient statistics can lose information about how well 
#the population distribution fits the observed data.

#Add a note hereCode Sample 4.3: Code sample for problem 4.6.

#if (/<TITLE>(.*)<\/TITLE>/)
#$count = 0;
#$title = $1;
#$count_e = 0;
#}
#else {
#$_=lc;
#s/[^a-z]//g;
#$count_e += tr/e/e/;
#$count += length;
#}

#Suppose we assume that this sequence is generated by a coin,
# where 1 stands for heads and 0 for tails. Assume that the probability of heads is p,
# which we wish to estimate. Assuming that this model is true, then the sufficient
# statistic for p is estimated by the number of 1’s divided by the number of flips,
# which gives 17/25=68%

#However, this data set does not look like it comes from flipping a coin because
# the 0’s and 1’s tend to repeat. For this problem, compute the probability of getting 
#the data in equation 4.12 assuming that a coin with p=0.68 is, in fact, used.

#If this probability is low, then the assumption of a biased coin model is cast into doubt.
# However, reducing the data set to the sufficient statistic for p makes it impossible 
#to decide on the validity of this coin model; that is, information is lost by ignoring 
#the original data in favor of the estimate p=0.68.

#Hint: see section 9.4.1 for one approach of estimating the probability observing
# equation 4.12 if seventeen 1’s and eight 0’s can appear in any order with equal probability.

#For more on sufficient statistics see chapter 10 of Lee Bain and Max Engelhardt’s
# Introduction to Probability and Mathematical Statistics [7]. In addition, the point 
#that the data set does have more information than the sufficient statistic is made in
# section 8.7 of John A.Rice’s Mathematical Statistics and Data Analysis

#For the normal distribution, the sample mean and sample standard deviation are
# sufficient for the population mean and population standard deviation. 
#See theorem 7.1.1 of James Press’s Applied Multivariate Analysis [103] for a proof.