#4.8 To randomize the words in a story requires two steps. 
#First, they must be identified. Second, they are stored and
# then permuted. The task of identifying the words is discussed in 
# section 2.4 (and see program 2.6). So here we focus on rearranging
# them. For each word, store it in a hash using a string generated by
# the function rand as follows.

#$permutation{rand()} = $word;

#Then print out the hash %permutation by sorting on its keywords 
#(either a numerical or an alphabetical sort works). Since the keywords are 
#randomly generated, the sort randomly permutes the values of this hash.